feat: Add 2 new templates for generative QA
deepset-ai/templates pull request #21
Opened 2023-02-10 15:33 UTC by erendabanlioglu

@tholor @tstadel I added your templates here but mark this PR as draft so we can work on template and comments before merging.

2023-02-14 10:07 UTC, tstadel commented
@erendabanlioglu let's use the same EmbeddingRetriever in the promptnode template and set `top_k` to 3 as well. 
@tholor we could also go for the large model. WDYT?

2023-02-14 10:09 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering.yaml
> +      temperature: 0.2
I would increase the temperature to 0.7-0.9 since we return 5 answers by default (controlled by the parameter `top_k`). With a temp of 0.2 I often find that the same answer is always returned.

2023-02-14 10:11 UTC, sjrl commented
> @tholor we could also go for the large model. WDYT?

I agree, I would go for the large flan-T5 model as well for the PromptNode template.

2023-02-15 17:18 UTC, tholor commented on pipelines/GenerativeQuestionAnswering.yaml
> +      temperature: 0.2
Agree!

2023-02-15 17:18 UTC, tholor commented on pipelines/GenerativeQuestionAnswering.yaml
> +      api_key: <API Token>
We most likely won't need `api_key` here once [this story](https://github.com/orgs/deepset-ai/projects/6/views/4?pane=issue&itemId=20014084) is done?

2023-02-15 17:18 UTC, tholor commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      model_name_or_path: google/flan-t5-base
As in the other comments: let's switch to `google/flan-t5-large`

2023-02-16 09:07 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering.yaml
> +      api_key: <API Token>
correct, will remove.

2023-02-16 09:25 UTC, erendabanlioglu commented
@tholor @sjrl @tstadel feel free to just edit the templates as you think it fits. I only added template you provided anyway :)

2023-02-16 09:27 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering.yaml
> +      presence_penalty: 0.1
@tholor Do you think it would be good to set the `top_k=3` here? The default is 5 and the extra answers may not be worth the extra monetary cost incurred to OpenAI.

2023-02-16 09:29 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 10 # The number of results to return
I apologize if this has been discussed already, but I would recommend pushing this down to `top_k=3`. Currently, there is no mechanism to check that the prompt length is not too long for the model. When using `google/flan-t5-large` the max length is 512 tokens by default and if the prompt is longer than this then the prompt is silently truncated I believe.

2023-02-16 09:31 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      default_prompt_template: question-answering # An optimized variant of BERT, a strong all-round model
@Timoeller Did you have a better default QA prompt template that we should use here instead?

2023-02-16 09:42 UTC, mkkuemmel commented on pipelines/GenerativeQuestionAnswering.yaml
> +    params:
Should we indicate here that an API key is required by adding the param with a dummy-value?

2023-02-16 09:46 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering.yaml
> +    params:
This was removed intentionally. See conversation [here](https://github.com/deepset-ai/templates/pull/21#discussion_r1107435378)

2023-02-16 10:28 UTC, mkkuemmel commented on pipelines/GenerativeQuestionAnswering.yaml
> +    params:
Ah, didn't see that for some reason

2023-02-27 10:58 UTC, tholor commented on pipelines/GenerativeQuestionAnswering.yaml
> +      presence_penalty: 0.1
Agree. `top_k=3` or even 2 seems a better default.

2023-02-27 11:12 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering.yaml
> +      presence_penalty: 0.1
added top_k: 3

2023-02-27 11:12 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 10 # The number of results to return
reduced top_k to 3

2023-02-27 11:21 UTC, mathislucka requested changes

2023-02-27 11:21 UTC, mathislucka commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +    type: BM25Retriever # Uses a Transformer model to encode the document and the query
I'd use an embedding retriever with the multiqa model instead of bm25

2023-02-27 11:21 UTC, mathislucka commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 3 # The number of results to return
topk of 3 with join documents will very likely exceed the max seq length for flan t5

2023-02-27 12:18 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 3 # The number of results to return
Yes, I agree, the max seq length for flan t5 looks to be 512 tokens compared to the 4096 of davinci from OpenAI. We should at least reduce to 2 and maybe even 1.

2023-02-27 13:04 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 3 # The number of results to return
Do you prefer 2 or 1?

2023-02-27 13:48 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 3 # The number of results to return
done

2023-02-27 16:58 UTC, tstadel approved these changes
After changing:
- use EmbeddingRetriever for promptnode pipeline
- adding top_k: 3 for promptnode pipeline
- upgrading to Haystack 1.14.0 schema (top_k requires)
it looks pretty good. How about changing the name of the promptnode pipeline to `GenerativeQA_with_PromptNode`?

2023-02-27 17:54 UTC, tholor commented
@tstadel Why did you increase top_k to 3 again? @mathislucka and @sjrl flagged correctly that this might go beyond the allowed context length of the flan model (512) leading to a truncated prompt and bad results.

2023-02-28 08:23 UTC, mathislucka requested changes

2023-02-28 08:23 UTC, mathislucka commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      func: join_documents # Specifies the Shaper function to use, here we want it to combine all documents into one
I think we need to convert documents to strings as the results will be suboptimal otherwise. See: https://deepset-ai.slack.com/archives/C02NR2F2W1H/p1677564631141669

2023-02-28 08:24 UTC, mathislucka commented
On a more general note: Why do we provide 2 QA templates for our users? I think this will lead to  confusion and they will be unsure what to use. The AnswerGenerator might also be deprecated in the future so why not just go with a single  template?

2023-02-28 08:27 UTC, mathislucka commented
For the naming, if we keep both templates I would rename to:

`Generative Question Answering GPT-3`
`Generative Question Answering Flan`

2023-02-28 08:39 UTC, tstadel commented
> @tstadel Why did you increase top_k to 3 again? @mathislucka and @sjrl flagged correctly that this might go beyond the allowed context length of the flan model (512) leading to a truncated prompt and bad results.

Sorry, will correct

2023-02-28 08:47 UTC, tstadel commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      func: join_documents # Specifies the Shaper function to use, here we want it to combine all documents into one
@mathislucka I commented in slack to. With 1.14.0rc2 I cannot reproduce this. Which version of Haystack were you using?

2023-02-28 08:48 UTC, tstadel commented on pipelines/GenerativeQuestionAnswering.yaml
> +      top_k: 3 # The number of results to return
```suggestion
      top_k: 1 # The number of results to return
```

2023-02-28 08:49 UTC, tstadel commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      top_k: 3 # The number of documents to return
```suggestion
      top_k: 1 # The number of documents to return
```

2023-02-28 08:51 UTC, sjrl commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      func: join_documents # Specifies the Shaper function to use, here we want it to combine all documents into one
With the additions shown [here](https://github.com/deepset-ai/haystack/blob/c3a38a59c0e7b82afcdfb033e0631868e3c6b896/haystack/nodes/prompt/prompt_node.py#L1001-L1007) to Haystack I didn't think it is necessary to use the documents_to_strings function since we only keep the `Document.content` when running the prompt node. This was included in Haystack v1.13.1 so if that version is still causing the problem outlined in the Slack comment then there is probably a bug.

2023-02-28 15:25 UTC, erendabanlioglu commented
> On a more general note: Why do we provide 2 QA templates for our users? I think this will lead to confusion and they will be unsure what to use. The AnswerGenerator might also be deprecated in the future so why not just go with a single template?

I am happy to show only one if "The AnswerGenerator" will be deprecated. WDYT @tholor @tstadel? (We can still keep templates here but show only the prompt node one in UI)

2023-02-28 15:30 UTC, tholor commented
Had a quick sync with @mathislucka about it after the daily: 
- let's keep both
- I don't see `AnswerGenerator` being deprecated in the next 3-6 months
- let's make sure that we point out the differences of both templates for users: 
-- names as @mathislucka suggested above highlighting GPT-3 vs. (open source) Flan
-- description of templates should point out the model differences + that the "flan prompnode" template is for advanced users who seek to have more control over the prompt (will make a suggestion in the template)

2023-02-28 15:51 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +# This is the Generative Question Answering pipeline for English with a good vector-based Retriever and Google's FLAN-T5 model.
Done

2023-02-28 15:51 UTC, erendabanlioglu commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      default_prompt_template: question-answering # An optimized variant of BERT, a strong all-round model
Since there was no comment from @Timoeller I am marking this as resolved, feel free to left comment and reopen.

2023-02-28 19:23 UTC, tstadel commented on pipelines/GenerativeQuestionAnswering_flan.yaml
> +        delimiter: " - "
```suggestion
    params:
      func: join_documents # Specifies the Shaper function to use, here we want it to combine all documents into one
      inputs:
        documents: documents
      outputs:
        - documents
      params:
        delimiter: " - "
      publish_outputs: false
```

2023-03-01 09:30 UTC, tstadel commented on pipelines/GenerativeQuestionAnswering_prompt.yaml
> +      func: join_documents # Specifies the Shaper function to use, here we want it to combine all documents into one
I quickly verified with 1.14.0 on dev: No document overheads, a prompt looks like this:
```python
>>> res["_debug"]["PromptNode"]["runtime"]["prompts_used"]
['Given the context please answer the question. Context: He continued by noting that Sheeran requested to change the key of the song that he performs in the scene during the episode\'s filming.\n\nGaztelugatxe in Spain was used for portions of the scene set on Dragonstone.\nPodeswa also discussed his direction for the cold open, saying he wanted to "honor the great writing", and praised Maisie Williams and David Bradley\'s performance as Arya Stark and Walder Frey respectively, stating "As we got more into it, you knew the audience would have questions coming right into the scene, knowing Walder Frey is dead. So, what is this? Is it a flashback? Is there something else going on here? It\'s about playing that line of audience surprise and curiosity and how they read the scene. David\'s performance is so fantastic where there\'s a moment you can almost feel Arya inside of him. It\'s even before the dialogue betrays who he is."The scene was not written as a cold open; Benioff and Weiss made that decision on the strength of Bradley\'s work. Following the cold open, Podeswa also spoke about directing the opening scene following the title sequence, revealing "We knew it would be one shot. Nothing fancy in terms of camerawork. But it\'s a shot that very slowly reveals itself over time, and we take that time. Then it was a matter of me conceptualizing it with the storyboard artists and visual effects department." - Matt Fowler of IGN described the episode as "amazing", saying "With Daenerys now in Westeros, war is imminent and worlds were colliding in this week\'s big episode."He gave the episode a 9 out of 10. Ben Philippe of \'\'New York Observer\'\' also gave a positive review, saying "\'Stormborn,\' proves that the table setting always pays off in Game of Thrones by giving us a sample platter of everything that the show does best."Nina Shen Rastogi of \'\'New York Magazine\'\' similarly gave praise to the episode, writing "All of this prologue is what made the final scene land so hard, and so well. The shipboard battle between the Greyjoys was very good GOT, in my mind: dramatic, unexpected, and authentic on a character level."Sean T. Collins of \'\'Rolling Stone\'\' praised the battle sequence at the end, writing "It ends with a naval battle as grandiose as any we\'ve seen in the series. But the strong second chapter of Game of Thrones\' seventh season - \'Stormborn\' - navigates even more treacherous waters."Erik Kain of \'\'Forbes\'\' gave a mixed review, writing that he enjoyed Arya\'s scenes but criticizing the Dragonstone scenes. Kain also criticized the plot hole of Ellaria Sand being in control of Dorne.\n\n===Accolades===\n\nYear\n\nAward\n\nCategory\n\nNominee(s)\n\nResult\n\n2017\n\nHollywood Post Alliance\n\nOutstanding Editing\n\nTim Porter\n\n==References==\n\n==External links==\n\n*  "Stormborn" at HBO.com\n*\n* - ===Writing===\nWriting for the eighth season started with a 140-page outline. Benioff said that the divvying up process and who should write what section became more difficult because "this would be the last time that they would be doing this."===Filming===\nIn an interview with \'\'Entertainment Weekly\'\', HBO programming president Casey Bloys said that instead of the series finale\'s being a feature film, the final season would be "six one-hour movies" on television. He continued, "The show has proven that TV is every bit as impressive and in many cases more so, than film. What they\'re doing is monumental."Filming officially began on October 23, 2017 and concluded in July 2018. Many exterior scenes were filmed in Northern Ireland and a few in Dubrovnik, Croatia; Paint Hall Studios in Belfast were used for interior filming. The direwolf scenes were filmed in Alberta, Canada.\n\n===Casting===\nThe eighth season saw the return of Tobias Menzies as Edmure Tully and Lino Facioli as Robin Arryn in the final episode, neither of whom appeared in the seventh season. Marc Rissmann was cast as Harry Strickland, the commander of the Golden Company.\n\n===Content===\nCo-creators David Benioff and D. B. Weiss have said that the seventh and eighth seasons would likely comprise fewer episodes, saying that after the sixth season, they were "down to our final 13 episodes after this season. We\'re heading into the final lap". ; Question: What is GoT?; Answer:']
```

2023-03-02 10:11 UTC, erendabanlioglu commented
If nobody has any other comments, I will be merging these after testing them. Thanks for the all input 💯

2023-03-02 11:21 UTC, tholor approved these changes

2023-03-02 12:20 UTC, merged