Fix: update haystack version
deepset-ai/templates pull request #39
Opened 2023-10-10 08:56 UTC by agnieszka-m

2023-10-10 15:11 UTC, ArzelaAscoIi approved these changes

2023-10-10 17:32 UTC, erendabanlioglu requested changes
@ArzelaAscoIi since you approved I'm asking you. Was backend moved to 1.21.2?

We need to upgrade UI first and deploy please don't merge it before.

2023-10-10 17:43 UTC, ArzelaAscoIi commented
Prod is on 1.21.2 already. (There shouldn't be any noticable change for the user though :) )

2023-10-19 12:27 UTC, erendabanlioglu commented
https://github.com/deepset-ai/haystack-hub-ui/pull/2421

2023-10-19 13:29 UTC, erendabanlioglu approved these changes

2023-10-19 13:35 UTC, merged